//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion
    {
        public int AsignacionID { get; set; }
        public Nullable<int> OrdenID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<int> ConductorID { get; set; }
        public int TurnoID { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual OrdenRecojo OrdenRecojo { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
