//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenRecojo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenRecojo()
        {
            this.Asignacion = new HashSet<Asignacion>();
        }
    
        public int OrdenID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaRecojo { get; set; }
        public string Horario { get; set; }
        public Nullable<int> EstadoOrdenID { get; set; }
        public Nullable<int> TipoResiduoID { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoOrden EstadoOrden { get; set; }
        public virtual TipoResiduo TipoResiduo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion> Asignacion { get; set; }
    }
}
